// <auto-generated />
namespace LFPEvents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialClean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialClean));
        
        string IMigrationMetadata.Id
        {
            get { return "202506241931052_InitialClean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
